### PR TITLE
Fix settings corruption

### LINKED ISSUE #159: App completely unuseable
**Platform:**
macOS Sierra 10.12.3
image

**Kap Version:**
1.0.1
### Steps to reproduce
Opening App. Nothing works. First attempted with a second display, but does not work with single display either.
### Current behaviour
It seems that no buttons are clickable. Nothing happens when I click buttons on the app. I cannot even quit the app without using the activity monitor.

screen recording 2017-03-23 at 12 50 pm
### Expected behaviour
I expect to be able to use the app.
### Workaround
 I have found no workaround. I even uninstalled the app and installed the latest update a month apart. Still have the same issue.

### PR DESCRIPTION
**Pull request by sindresorhus**
This sets the default settings no matter what. Previously it would not be set if the Aperture called failed.

Fixes #159

### CODE REVIEW

**Comment by sindresorhus** [comment]
@torkiljohnsen @iamtirado @andreleon Can you try it out?

You can download it here: https://kap-artifacts.now.sh/settings-corruption
Make sure you delete `~/Library/Application Support/Kap` first.

The call to get the microphone might still fail, so let me know if it does, so I can find a way to handle it.

**Comment by torkiljohnsen** [comment]
Not sure what you mean by the call to get the microphone, but I can't record with sound if that's what you're asking. Have no sound input to select either.

image

Also, when opening Kap I get this error:
skjermbilde 2017-05-18 kl 12 57 55

Other than that, it seems to be capturing just fine now 👍

**Comment by iamtirado** [comment]
This app is wonderful. Glad I can record with it now.

I probably won't use audio much, but I have the same audio issue as @torkiljohnsen where I can't select audio input and I also get the same popup at beginning.

**Comment by sindresorhus** [comment]
@torkiljohnsen Can you go to `Kap.app/Contents/Resources/app/node_modules/aperture/index.js` and change line 19 to the following:

```js
return execa.stdout(path.join(__dirname, 'swift/main'), ['list-audio-devices']).then(x => Promise.reject(new Error(x)));
```

And then run Kap and paste the error message here?

**Comment by torkiljohnsen** [comment]
image

**Comment by iamtirado** [comment]
my error: is it different? 
image

**Comment by sindresorhus** [comment]
Thanks for the help debugging this.

@torkiljohnsen Looks like you have an outdated version of the Bartender app installed or some remainders of it: https://webcache.googleusercontent.com/search?q=cache:lW3xY3OCuLUJ:https://origin-discussions-us.apple.com/thread/7286340+&cd=1&hl=en&ct=clnk&gl=th&lr=lang_en%7Clang_no

@iamtirado I think it's because we're by mistake building the binary in debug mode.

Can you both download and unzip [this](https://www.dropbox.com/s/rgled65edanlpgv/aperture%20main.zip?dl=0) and replace `Kap.app/Contents/Resources/app/node_modules/aperture/swift/main` and then start Kap?

**Comment by iamtirado** [comment]
Something changed in the debug log, but still can't select audio.
image

**Comment by torkiljohnsen** [comment]
@sindresorhus Indeed I had some old Bartender2 stuff around :) 

Replaced the `main` file and got this error when starting Kap:
image

Still no input devices.

image

**Comment by sindresorhus** [comment]
Alright. Can you try out https://kap-artifacts.now.sh/settings-corruption It should work now. Let me know.

**Comment by sindresorhus** [comment]
@iamtirado @torkiljohnsen Would you be able to confirm ⬆️ it's fixed?

**Comment by iamtirado** [comment]
I get the following error upon opening.



I can record my screen. Audio input is working, and all ui seems to be functional. When I go to save to gif, mp4, or webM the window for choosing save location closes, and the file never saves. Preview window stays open. so I can keep watching what I just recorded, but it doesn’t save. Nothing happens when I hit save.

—
Eric Tirado
Brand Design | Web Development
erictirado1@gmail.com
678-577-8064

**Comment by CodeTheory** [comment]
The error you're getting is normal for a build artifact. 

Are you sure it's not saving? The new behaviour of Kap is to let the editor remain open after saving so that you can perform multiple export actions. Did you check that the file is not in the location that you requested it to be saved in?

**Comment by iamtirado** [comment]
Yes i saved to desktop and other places and food not see the file.

**Comment by sindresorhus** [comment]
Merging as it fixes what it was intended too. We'll look into the file not saving thing.

**Pull request merged**
