### PR TITLE
This is wiki for Kap user documentation

### PR DESCRIPTION
**Pull request by genesis-writing**
I decided to build a user guide for Kap as I have been using it for the past few years and been very happy since. I have enjoyed its simplicity but had to find my way around its interface on my own as I could not find user-oriented documentation. 

This is my very first pull request ever, any feedback whatsoever is more than welcome.

### CODE REVIEW

**Comment by timothyis** [comment]
Hi @genesis-writing, thanks for taking the time to submit this pull request. 

May I ask where the images are used in this pull request?

**Comment by genesis-writing** [comment]
Good evening @timothyis, I uploaded the images within a directory titled "wiki_images". Apologies if I am misinterpreting your question, this is new territory for me.

**Comment by timothyis** [comment]
No worries at all! I'm just wondering what the images are for. Are they used in documentation somewhere? 

I think documentation would be great, but I do think that it belongs on the [Kap website](https://github.com/wulkano/getkap.co).

**Comment by genesis-writing** [comment]
Ah yes! Correct, the images are for the user help guides. Thank you so much for pointing me in the right direction @timothyis , really kind of you. As a next step, would you recommend I close this request and make the contribution to the getkap.co repo instead?

**Comment by timothyis** [comment]
I would indeed @genesis-writing, however, I'll also ping @skllcrn here to see what he thinks about adding one before you do. 🙏🏼

**Comment by genesis-writing** [comment]
Thank you @skllcrn, for your review! Perhaps that FAQ repo doc will be my next step then. I will be closing this request now.

**Pull request closed without merging**
