### PR TITLE
Use input type password

### PR DESCRIPTION
**Pull request by ochorocho**
Use input type password for config fields in plugins containing "password" in name.

Example Plugin config

```
...
password: {
      title: 'Password',
      type: 'string',
      required: true
},
...
```
Result:

bildschirmfoto 2019-02-02 um 19 12 54

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's too fragile to just check the title. Having a password field might not be what the author wants, even if the title contains the word "password".

Instead, we should add a custom [`ajv`](https://github.com/epoberezkin/ajv) password type.

I imagine it would look like this then:

```js
password: {
      title: 'Password',
      type: 'password',
      required: true
},
```

**Comment by sindresorhus** [comment]
It's not enough to just create the keyword. We also need to check for it in the settings window renderer and use a `<input type="password">` instead of normal input if it's a `type: 'password'`.

**Comment by skllcrn** [comment]
Just checking in, are you still wanting to wrap this one up @ochorocho?

**Comment by ochorocho** [comment]
Well, i can't get this working. Due to lag of Javascript knowledge. But it would be great to have such a addtional field.

**Comment by sindresorhus** [comment]
@ochorocho Can you open a new issue about this instead?

**Pull request closed without merging**
