### PR TITLE
Fix `Do Not Disturb` persistence issue

### LINKED ISSUE #433: On Mac, Notification Center "Do Not Disturb" setting becomes permanent
I updated to v2.1.0. I noticed the "DND" option was checked by default, so I unchecked it immediately. I recorded something. 

A few minutes later, I notice I'm not getting any notifications. I see that Notification Center is disabled, "until midnight". I enable it. I restart my Mac. Notification Center is once again disabled.

I open `~/Library/Preferences/ByHost/com.apple.notificationcenterui.<guid>.plist`. I see that `dndStart` is set to `0` (indicating 0:00 on a 24-hour clock, I assume) and `dndEnd` is set to `1440` (indicating 24:00). This means that I won't be getting notifications forever. I manually change both values to `0` (or alternatively, you can delete them), and I restart my Mac. Notification Center is enabled. The [post here](https://discussions.apple.com/thread/7604851) was useful in fixing this.

This started with this update.

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #433

### Changes:
- Don't turn DND on if the user already has it on
- Default DND setting to off
- Add 'Experimental' flag

### CODE REVIEW

**Comment by karaggeorge** [comment]
Also opened a PR for do-not-disturb package to try a less evasive way of enabling DND, so even if for some reason we don't clean it up, a user can disable it normally in the Notification Center

https://github.com/sindresorhus/do-not-disturb/pull/4

**Comment by sindresorhus** [comment]
> Don't turn DND on if the user already has it on

Should we maybe do this in the Swift package too? I mean, make `enable()`/`disable()` moot if already in that mode.

**Comment by karaggeorge** [comment]
@sindresorhus I think that's a good idea: https://github.com/sindresorhus/do-not-disturb/pull/4/commits/f555da09d2935020555ad0664dda7ca83828e1e3

**Comment by sindresorhus** [comment]
Thanks for fixing, @karaggeorge 🙌

**Pull request merged**
