### PR TITLE
Close preferences window before recording

### PR DESCRIPTION
**Pull request by karaggeorge**
This is to avoid a number of weird bugs around changing recording settings while actually recording

### CODE REVIEW

**Comment by karaggeorge** [comment]
@sindresorhus how can you get to it while recording? The action bar hides and the tray icon turns into the stop recording button

**Comment by sindresorhus** [comment]
I can also right-click the menu bar icon during recording to get to `Preferences…`.

**Comment by karaggeorge** [comment]
@sindresorhus that's true.

This is a different approach: https://github.com/wulkano/kap/pull/523

If we still want to keep this and hide the Preferences, I'll work on updating it but it doesn't need to be in the beta

**Comment by sindresorhus** [comment]
> If we still want to keep this and hide the Preferences, I'll work on updating it but it doesn't need to be in the beta

What's your opinion? I think it's sensible to disable `Preferences…` during recording. We can actually just disable right-click on the icon altogether during recording instead.

**Comment by karaggeorge** [comment]
Yeah I think that's the easiest way to eliminate all edge cases

**Comment by karaggeorge** [comment]
@sindresorhus This should be good now

**Pull request merged**
