### PR TITLE
Standardizes the size of SVG icons

### LINKED ISSUE #564: The cropper control icons looks like they have different sizes
Would be good to visually unify them.

screen shot 2018-10-04 at 13 03 40

Slack discussion:

screen shot 2018-10-04 at 13 04 11

### PR DESCRIPTION
**Pull request by pauloedurezende**
Fix #564

### CODE REVIEW

**Comment by skllcrn** [comment]
Thank you @pauloedurezende, and congrats on your first! Does this edit the actual SVG's/icons themselves, or just the bounds? We've been very careful with using customised icons as it can quickly lead us down the path of inconsistency. If this does tweak the actual paths we should make sure to contain it to the toolbar and leave sufficient context. Could you post a Kapture which also shows the hover and active states?

**Comment by sindresorhus** [comment]
I think it would be better to set a correct `viewBox` attribute on all those icons. Then we can just use the width/height attributes.

**Comment by pauloedurezende** [comment]
> Thank you @pauloedurezende, and congrats on your first! Does this edit the actual SVG's/icons themselves, or just the bounds? We've been very careful with using customised icons as it can quickly lead us down the path of inconsistency. If this does tweak the actual paths we should make sure to contain it to the toolbar and leave sufficient context. Could you post a Kapture which also shows the hover and active states?

Thank you! I had only changed the sizes of the icons in SVG, I left them all with a fixed size (18px if I'm not mistaken).

> I think it would be better to set a correct `viewBox` attribute on all those icons. Then we can just use the width/height attributes.

I agree that as I had done, it was not the best way, I returned the icons the way they were and added the `viewBox` as you mentioned.

It ended up having the same aesthetic result as the GIFs below...

Using the edited SVG icons:
edited svg

Using `viewBox`:
viewbox

**Comment by sindresorhus** [comment]
@pauloedurezende The `viewBox` attribute should be added to the components themselves, not where they are used.

**Comment by sindresorhus** [comment]
@pauloedurezende Still interested in finishing this? :)

**Comment by pauloedurezende** [comment]
@sindresorhus  Yes I am, sorry for the delay...

But one thing I can not understand, the SVG components, such as `crop.js`, it gets the props and goes to the `svg.js` component. In this component, it has its default properties, where it ends up passing to `<svg></svg>`. So, it would not be more logical to end up using the `crop.js` component, for example, this way `<CropIcon viewBox="-1.75 -1.75 28 28" onClick={toggleAdvanced} />`, instead of having to change the component itself, to stay this way `<Svg {...props} viewBox="-1.75 -1.75 28 28">[...]</Svg>`?

**Comment by sindresorhus** [comment]
@pauloedurezende I don't fully understand your question, but the `viewBox` should be added to the icon components themselves as it's internal data that you should not need to know outside the specific icon component. I would recommend reading up on the `viewBox` attribute.

**Comment by sindresorhus** [comment]
It looks better now than what's in master branch, but I still feel the sizes could be improved. Not sure yet what bothers me.

Here's how it looks now:

screen shot 2018-12-18 at 15 32 06

@skllcrn Thoughts?

**Comment by skllcrn** [comment]
In that last screenshot both the cropper and fullscreen icon areblurry at @1x and not particularly well balanced in terms of visual weight. They should stick to the standard icon size and sit inside 24x24 bounds. We can [try using another icon](https://github.com/google/material-design-icons/blob/master/image/svg/production/ic_crop_free_24px.svg) for the fullscreen option if that's the one that's bothering you.

**Comment by sindresorhus** [comment]
Closing as this doesn't correctly fix the issue and we're not really sure in which way to fix it ourselves. We still need to do something about the icons, but I'm not sure what...

**Pull request closed without merging**
