### PR TITLE
Update hide-desktop-icons dependency to make it work with ASAR

### PR DESCRIPTION
**Pull request by karaggeorge**
As per https://github.com/karaggeorge/hide-desktop-icons/issues/4

Fixed in: https://github.com/karaggeorge/hide-desktop-icons/commit/71c477e855406dc5310d1f18305054bb35b503c3

### CODE REVIEW

**Comment by karaggeorge** [comment]
This https://github.com/karaggeorge/mac-windows/issues/1 was also implemented and published. Should I update that dependency as well in this PR?

**Comment by albinekb** [comment]
I say go ahead @karaggeorge 👍

**Comment by karaggeorge** [comment]
@sindresorhus has mac-windows been working fine in the packaged versions of kap? I didn't use the ASAR path in that either. Should I update that one too?

**Comment by sindresorhus** [comment]
> has mac-windows been working fine in the packaged versions of kap? I didn't use the ASAR path in that either. Should I update that one too?

It's working fine since you're using `childProcess.execFile`, which is patched by Electron. Electron just left out `spawn`, which `execa` uses, which is why we have to do this dumb workaround. See: https://github.com/electron/electron/issues/9459

**Pull request merged**
