### PR TITLE
Fix cropper window

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
Fixes https://github.com/wulkano/kap/issues/111

### CODE REVIEW

**Comment by Khaledgarbaya** [comment]
@matheuss  @sindresorhus @CodeTheory any progress on this ?

**Comment by CodeTheory** [comment]
Sorry for the delay @Khaledgarbaya. It's been a busy delay for all of us. I'll get one of the team to review it this week. ❤️

**Comment by doot0** [comment]
Hey @Khaledgarbaya. Taking a quick look at your PR (thank you by the way!), LGTM.

I'm wondering if perhaps the following is a bit more readable however;

```
const dimension = 512;

let {width, height} = settings.get('cropperWindow.size');
width = size.width || dimension;
height = size.height || dimension;
```

Would like your thoughts. :)

**Comment by Khaledgarbaya** [comment]
hi @doot0 ,
In your snippet, getting the width and height from the settings will be broken.

```js
let {width=512, height=512} = settings.get('cropperWindow.size');
```
☝🏼 what that snippet is doing is checking for example if the settings had already some value for the width otherwise it will assign 512 to it, same for height.

and for 

```
width = size.width || width;
height = size.height || height;
```
will check  if there is a size.width, and size.height otherwise it will stick with the default values saved in the settings.

Let's take this scenario 
You open the app first time and you set the copper dimension. Kap should save that in the settings.
when you come back 

```js
let {width, height} = settings.get('cropperWindow.size');
```
☝️ should have the values from your settings. But

```js
width = size.width || dimension;
height = size.height || dimension;
```
☝️ will set the width and height to dimension if the size is not provided, which will break the feature of saving the last saved setting

**Comment by doot0** [comment]
LGTM. 👍

**Pull request merged**
