### PR TITLE
Persist format-specific fps options

### LINKED ISSUE #861: Persist FPS on a format basis
We persist fps across editors and launch, but we only remember one value. Most people don't usually export with the same fps for every format.

For example, I usually export mp4 with 60fps, and gif with 15fps. So, even though we persist fps, I still have to change it quite often.

I think we should remember the last used fps for each format, same as we do for plugin usage etc

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #861

### CODE REVIEW

**Comment by sindresorhus** [comment]
In the editor, I have "GIF" active, I set FPS to 10, then switch to MP4 and then back to GIF again and it's no longer 10. I think it should be persisted there too.

**Comment by karaggeorge** [comment]
I had it persisting every time you actually export with that value, thinking that in normal use you wouldn't be switching back and forth between formats. Should I persist every time the fps value changes for each format?

**Comment by sindresorhus** [comment]
> Should I persist every time the fps value changes for each format?

It's probably an edge-case, but that's what I would expect as a user.

**Comment by karaggeorge** [comment]
@sindresorhus this is ready for another look 😄

**Pull request merged**
