### PR TITLE
Export window updates

### LINKED ISSUE #537: Clicking an item in the Exports window should reveal the file in Finder
That's what I expected to happen. It's weird that it currently has a hover effect, but nothing happens when I click it.

### LINKED ISSUE #543: Add a way to open export window
**Kap version:** 3 Beta 1

#### Current behaviour
Can't open export window after closing it

#### Expected behaviour
I can open up the export window in the menu bar or cropper controls:
image

#### Workaround
Record & export another recording to get the export window to show

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #543 
Fixes #537 

Partially addresses #538 by printing export errors in the devtools when an export fails

### CODE REVIEW

**Comment by sindresorhus** [comment]
The `Export completed` text should not be selectable.

**Comment by sindresorhus** [comment]
I exported a GIF to disk and when clicking the item in the export window, nothing happens still.

**Comment by sindresorhus** [comment]
Another thing I noticed is that the menu shown when clicking `...` is incorrectly placed based on mouse location and not the `...` location. So https://github.com/wulkano/kap/pull/528#discussion_r221130376 would be useful here too.

**Comment by karaggeorge** [comment]
Hmm, @sindresorhus the click to open was working for me and now it's not. After inspecting and grabbing the filepath, seems like the file doesn't exist any more. Is it possible that because it's in a temp directory it gets cleared at some point?

**Comment by sindresorhus** [comment]
@karaggeorge Temp directories doesn't clear out that fast, but it is moved: https://github.com/wulkano/kap/blob/8caadd8e3abdd1dcae1d51a72a2029f182c1ee87/main/save-file-service.js#L14

**Comment by karaggeorge** [comment]
😮 I don't know how I missed that. That's why it was working before. I was using a different export method. I can change that so it copies instead 👍 

Good catch!

**Comment by karaggeorge** [comment]
@sindresorhus This should be ready and now fixes #538 as well. The only thing left out is the `...` menu not opening right which I'll fix with the reusable select in the other PR

**Comment by sindresorhus** [comment]
>  I don't know how I missed that. That's why it was working before. I was using a different export method. I can change that so it copies instead 👍

I didn't mean that you should change the moving. The point of the "revealing in Finder" is to show it where it ended up. For "Save to Disk" this should use `targetFilePath`, for other services, we can just reveal it in the temp directory.

**Comment by sindresorhus** [comment]
👌

**Pull request merged**
