### PR TITLE
Add tab support to the cropper

### LINKED ISSUE #136: UX Improvement: Update control panel tabindex
**As a keyboard shortcut power user**, I would love to be able to jump between input fields `width` and `height` with a single `TAB` press.

Currently, the `tabindex` is completely linear, so there's **three** tab presses to get from `width` to `height`, although the two steps in between doesn't have any actual interactions.

_e.g: There's no highlighted state for the two buttons in between `width` and `height`, and I can't trigger either button with `Enter`._

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #136 

Used the last commit of #593 as the first ones seemed to all be reverted and built on it

### CODE REVIEW

**Comment by karaggeorge** [comment]
@sindresorhus Should be fixed

**Comment by karaggeorge** [comment]
- Ah, I didn't know the <kbd>↓</kbd> was standard behavior. I can add it. Do we have to remove the <kbd>↵</kbd> button, or can that stay? 
- I would think <kbd>↵</kbd> would be better than <kbd>space</kbd>
- Is that something we want? / what would that focused state look

**Comment by karaggeorge** [comment]
To me, space feels like it's for selecting apps (because of how close this behavior is to the native screenshot tool), but I could go either way.

Also, what's the default `focus` state for the record button? I has none right now

**Comment by sindresorhus** [comment]
> * I think we should remove ↵ as that's typically reserved for making a selection within the `select` and to submit the entire form @karaggeorge, but I'll defer to @sindresorhus on this.

Correct. Only `↓`.

**Comment by skllcrn** [comment]
For the record button I think it makes the most sense to invert it @karaggeorge
 
image

**Comment by karaggeorge** [comment]
@skllcrn @sindresorhus 

Changed the menus so now they are opened by the arrow and not enter or space. (might be hard to identify since the regular buttons and the dropdowns don't look any different), and also added focused state to the record button.

Do we still want the global enter/space key to start recording? Or are those okay to being applicable when the record button is focused?

**Comment by skllcrn** [comment]
For now I suggest just supporting <kbd>↵</kbd> when focused on the record button. We can look more into a dedicated keyboard shortcut to start the recording separately.

**Comment by sindresorhus** [comment]
I'm not seeing any record button focus state.

**Comment by sindresorhus** [comment]
If I click the record button right after starting up, it looks a bit weird:

screen shot 2019-02-07 at 02 22 46

**Comment by karaggeorge** [comment]
@sindresorhus should be good

**Comment by sindresorhus** [comment]
Looks good 👍

**Pull request merged**
