### PR TITLE
Export gifs to s3

### PR DESCRIPTION
**Pull request by cameronmaske**
Hi,
I took a stab at adding some upload to s3 functionality. 
image
(Upload button added)
After uploaded, copies the URL to clipboard.
image

Here is a gif recording of what it looks like! 
https://camerons-amazing-gifs.s3.amazonaws.com/lOHsGsJ1qUoGKTmlrQC8vSho.gif

I also added a 3rd tab to the pref. to set S3 creds. 
image
(Needs a bit of styling love. I can't seem to get the tab to be marked as "active").

This is very much a quick implementation (I haven't used electron before, so any advice is welcome) and welcome any feedback/thoughts!

### CODE REVIEW

**Comment by skllcrn** [comment]
This is really cool @cameronmaske! We've got a few issues regarding uploading to various sites and hosting solutions, see [my comment](https://github.com/wulkano/kap/issues/147#issuecomment-280944691) on #147. 

Additional exporting and uploading options are some of the most requested features, at the same time we want to keep the core Kap app as nimble as possible. To cater to all the different needs people have we've started planning a plugins system, which we hope to ship in the next big version of Kap. 

Think of it as making Kap modular, where developers power users can extend the functionality of Kap to their own liking. 

What you've made here would be perfect as a plugin and helps validate the effort. I'll put this issue on hold for now and keep you updated here. Really hope to see this as a plugin soon!

**Comment by cameronmaske** [comment]
Sure @skllcrn makes sense. Would y'all mind if I packed a version of Kap from this branch, and hosted the install on my fork until Kap 2.0 ships? Just as a stop gap for any devs who want some "early access" to s3 capabilities?

**Comment by CodeTheory** [comment]
Go for it @cameronmaske. Open source <3

**Comment by sindresorhus** [comment]
@cameronmaske Hey. Nice work on this. I published a [proposal for how the plugin system should work](https://github.com/wulkano/kap/issues/181) and I already started implementing part of it with the goal of having something working in a couple of weeks. Comment there if you have any concerns or if I missed something that will be needed to implement this as a plugin.

**Comment by CodeTheory** [comment]
Hey @cameronmaske! Would you want to put this into a plugin?
We have docs coming here: #190 
and a plugin example here: https://github.com/wulkano/kap-giphy

**Comment by SamVerschueren** [comment]
Hi everyone! I already created an S3 plugin for Kap and will release it any moment. Just wanted to let you guys know so that we aren't doing double work :).

**Comment by SamVerschueren** [comment]
Here it is https://github.com/SamVerschueren/kap-s3

**Comment by cameronmaske** [comment]
Awesome <3

**Pull request closed without merging**
