### PR TITLE
Add CSS linter

### PR DESCRIPTION
**Pull request by sindresorhus**
There are many people contributing to the CSS parts now. This will make it easier to enforce a clean and maintainable codebase.

This touches a lot of CSS, so let's have code style discussions later.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Happy to change anything. As I said on Slack, this is just a good start.

**Comment by sindresorhus** [comment]
@CodeTheory What do you think of this rule: https://github.com/stylelint/stylelint/blob/c85372c07239e2d0688abcda1eb1b390e649bfba/lib/rules/no-descending-specificity/README.md ? I had to disable it here as it had too many violations.

Same with https://github.com/stylelint/stylelint/blob/c85372c07239e2d0688abcda1eb1b390e649bfba/lib/rules/declaration-no-important/README.md

**Comment by CodeTheory** [comment]
Both good rules @sindresorhus. First avoids a lot of un-necessary hassle and the second is just a good rule of thumb (same with the hassle).

**Comment by sindresorhus** [comment]
Alright. I'll try to enable them at some point. When we can afford some churn.

**Comment by CodeTheory** [comment]
If you don't around to it, I'll give it a go @sindresorhus. Should we open a separate issue for them or just try to remember.

**Comment by sindresorhus** [comment]
Feel free to give it a go. I'm just a CSS noob.

**Comment by sindresorhus** [comment]
I opened an issue: https://github.com/wulkano/kap/issues/285

**Pull request merged**
