### PR TITLE
Center cropperWindow inside the focused display #131

### LINKED ISSUE #131: Kap always shows marquee on 'system' display.
**Platform:**
Darwin Steves-iMac.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

**Kap Version:**
1.0.0 (1.0.0.134)

### Steps to reproduce
With multiple screens attached to a desktop Mac, open Kap from a Finder window on the non-System* display.  (* where the menu bar is dragged in the Mac's Display system preference)

Click on the red 'select recording area' tool in Kap.

### Current behaviour
The marquee always appears on the Mac's *system* display, not the display I launched Kap on.

### Expected behaviour
Should show the marquee on the screen I launched Kap on, where I want to do my recording.

### Workaround
Drag marquee from the System display over to one of the other displays,.

### PR DESCRIPTION
**Pull request by catalinmiron**
Closes #131

### CODE REVIEW

**Comment by catalinmiron** [comment]
@karaggeorge thanks for reviewing the code. It doesn't happen for me actually. I have 3 displays (primary display, my macbook, and two other displays) and if I don't move the cropper window (storing the position) when I'm opening the cropper again in a different display it will center in that particular display. But after moving the cropper and have stored the coordinates (x, y) then, after opening the cropper again, it will open in the previous location.

Please check the uploaded video:
https://www.youtube.com/watch?v=3gbvZYtCHgY

Thanks!

**Comment by catalinmiron** [comment]
If you're talking about a different os (other than macosx) I think that we can recalculate the coordinates with `getDisplayNearestPoint()` for `getCursorScreenPoint` like `screen.getDisplayNearestPoint(screen.getCursorScreenPoint()).bounds` and then recalculate the `x, y` based on that position. 

```js
const getCropperXYCoordinates = ({position, width, height}) => {
  let {x, y} = settings.get('cropperWindow.position');

  if (position.x && position.y) {
    return {...position};
  }

  // check if x and y has a predefined position, otherwise calculate the center of the focused window.
  // 'center' is the default value for x and y and so we know that there so no predefined value for them.
  if (x === 'center' && y === 'center') {
    let bounds = screen.getDisplayNearestPoint(screen.getCursorScreenPoint()).bounds;
    let centeredX = Math.ceil(bounds.x + ((bounds.width - width + cropperWindowBuffer) / 2));
    let centeredY = Math.ceil(bounds.y + ((bounds.height - height + cropperWindowBuffer) / 2));

    return {x: centeredX, y: centeredY};
  }

  return {x, y};
}

// in openCropperWindow

let {x, y} = getCropperXYCoordinates({position, width, height});

new BrowserWindow({
  // ...
  x,
  y
})
```

**Comment by catalinmiron** [comment]
@karaggeorge I have to push some more commit in order to get everything up and running. I'm also thinking that we are hardcoding the `fullscreen` coordinates (x,y) values to `{x: 0, y: 0}` which is not true when using multiple displays. Please stop reviewing the code, I'll ping you once this is ready for review. Thanks!

**Comment by karaggeorge** [comment]
@catalinmiron I'll take another look, I might have missed something. As for the fullscreen, if you are referring to us setting x and y to 0 right before recording (for aperture), that is the desired behavior, since we need them to be relative to that display in that case.

**Comment by catalinmiron** [comment]
@karaggeorge what do you think about this approach for fullscreen? :)

image

**Comment by skllcrn** [comment]
That's not a bad idea @catalinmiron, but I'd be hard pressed to know which is which based on "Secondary display 1" and "Secondary display 2", would probably need a preview. The simplest solution is to go fullscreen on the active display, the one Kap was triggered on. That's what we're doing in the `[next](http://kap-artifacts.now.sh/next)` branch too: https://github.com/wulkano/kap/pull/450

**Comment by catalinmiron** [comment]
@karaggeorge everything should be fixed now. Including fullscreen and changing the ratio. For changing the ratio, I'm using `setBounds` with animation and reuse the `getCropperXYCoordinates`. Please take another look and let me know if this code look better. 

cc: @sindresorhus if you also have some time to take a look.

Thanks!

**Comment by karaggeorge** [comment]
@catalinmiron I just checked out the latest commit of the PR and tried it locally but the cropper shows up in the wrong display. Please take a look at the video [here](https://www.dropbox.com/s/6hvr7llherzl88j/VID_20180516_104950.mp4?dl=0).

I think that happens because the `{x, y}` coming from the settings has the location of the last opened cropper. So, in the logic you have, it will follow the first `if` but not the second. So, it will open it in the last position.

I think you had it almost right with your initial solution. Try checking if there is an x and y in the `position` object. If there is, we use those relative to the current display. If not, try getting the x, y, width, height of the last cropper from the settings. Use those along with `screen.getDisplayMatching(rect)` to find what screen that cropper belonged to. Then find the currently active screen using `screen.getDisplayNearestPoint(screen.getCursorScreenPoint())` and compare their ids. If they are the same, use that x, y, width, height. If not, pass in `center: true`.

**Comment by skllcrn** [comment]
https://github.com/wulkano/kap/pull/466

**Comment by catalinmiron** [comment]
@karaggeorge @skllcrn would you like to continue working on this? I saw that there's a PR conflict. Thanks!

**Comment by skllcrn** [comment]
I suggest you and @nnnoel agree on which PR is best to continue off and look into the feedback from @karaggeorge (https://github.com/wulkano/kap/pull/461#issuecomment-389551292). Then you can help each other wrap it up and review!

**Pull request closed without merging**
