### PR TITLE
added in ava test

### PR DESCRIPTION
**Pull request by dhuang612**
trying from a fresh updated copy of the repo seeing if it can pass continuous integration test.

### CODE REVIEW

**Comment by dhuang612** [comment]
still having the same issue of it not running the test at all.
included an env param which didn't resolve anything

**Comment by dhuang612** [comment]
This is pending the circleci update

**Comment by skllcrn** [comment]
This seems like a great starting point @dhuang612, but I'm not sure it fully addresses #27. From what I can tell this adds a test to check if there is a window in addition to dev tools, but that doesn't really tell us much. The tests issue is quite old and would definitively benefit from some more specs.

**Comment by albinekb** [comment]
Since Kap is macOS only, I don't see how a docker image would make tests work? From what I know it's not possible to run the app inside docker? 🤔 The test needs to be ran with macOS?

**Comment by karaggeorge** [comment]
@skllcrn @albinekb @dhuang612 

I think the miss-understanding comes from the issue itself. We need tests, but there's two types of tests. Pure js unit tests and e2e tests.

Spectron is used for e2e tests and you need the app to run in a macOS image, which is not supported by CircleCI right now, and we'd have to set up our own image. However, like @skllcrn said, there's little to no value in writing Spectron tests, as you can't really test functionality past how many windows are open which is not worth the set up.

So, what we are really looking for in adding tests, is adding simple js unit-tests using AVA, to test parts of the app like conversion logic, helper functions and maybe setting up frontend React tests. 

For those, we don't need the whole app to run in an environment, we just need to import those specific js files.

A good start would be setting up tests for our conversion logic in the `main` part of the app

**Comment by dhuang612** [comment]
@karaggeorge 

Thank you, that explains a lot of what I wasn't understanding!

I can start on that and will work to get that completed.
I'll go ahead and close this pr since it's not relevant.

**Pull request closed without merging**
