### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by karaggeorge** [comment]
There's a couple of issues with this when packaged:

1. New Next.js update broke the packaged file path location, which I fixed locally 
2. Aperture devices are not working when packaged (for preferences). Investigating that now

**Comment by karaggeorge** [comment]
@sindresorhus I was able to track the error down. Only happens when the app is packaged:

```
commons.98e96a5dd8123df2281b.js:1 Uncaught (in promise) TypeError: stdout Cannot read property 'on' of undefined
    at /Applications/Kap4.app/Contents/Resources/app.asar/node_modules/get-stream/index.js:43
    at new Promise (<anonymous>)
    at getStream (/Applications/Kap4.app/Contents/Resources/app.asar/node_modules/get-stream/index.js:25)
    at getStream (/Applications/Kap4.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:135)
    at handlePromise (/Applications/Kap4.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:270)
    at ChildProcess.spawned.then (/Applications/Kap4.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:312)
    at Function.module.exports.stderr (/Applications/Kap4.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:322)
    at module.exports.audioDevices (/Applications/Kap4.app/Contents/Resources/app.asar/node_modules/aperture/index.js:160)
    at Object.getAudioDevices (/Applications/Kap4.app/Contents/Resources/app.asar/main/common/aperture.js:198)
    at electron/js2c/browser_init.js:6552
```

The error happens here in aperture:
```
const stderr = await execa.stderr(BIN, ['list-audio-devices']);
```

Not sure if it affects anything, but aperture uses `execa@1.0.0` and Kap uses `execa@3.3.0`

**Comment by karaggeorge** [comment]
Hmm, we also can't fetch plugins from npm:

```
ReadError: Cannot read property 'on' of undefined
    at EventEmitter.<anonymous> (/Applications/Kap4.app/Contents/Resources/app.asar/node_modules/got/source/as-promise.js:28:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Both working in master build, so some dependency here is affecting them

**Comment by karaggeorge** [comment]
When I run the packaged app from CircleCI, I can't even start it 😮 

Screenshot 2019-11-14 11 23 00

Something is really messed up.

I opened a PR (based on this) to update and use the new `openSystemPreferences` method from `electron-util`, and did some cleanup on the preferences stuff. Noticed the issue with the new Next.js and fixed the path there as well, but getting the same issues:

https://github.com/wulkano/kap/pull/751

**Comment by sindresorhus** [comment]
> Not sure if it affects anything, but aperture uses execa@1.0.0 and Kap uses execa@3.3.0

It's a problem in latest `execa` too: https://github.com/sindresorhus/execa/issues/389

> When I run the packaged app from CircleCI, I can't even start it 😮

That's not a new issue. Sometimes code signing fails in CircleCI.

---

It really seems like Electron 7 broke Node.js streams somehow as we have two stream errors from two different packages.

**Comment by karaggeorge** [comment]
Yeah, that sounds like the best guess. Surprisingly I can't find related issues on electron's repo. Not sure what we can do about this, other than wait

**Comment by sindresorhus** [comment]
@karaggeorge Doesn't look like this will be fixed in Electron anytime soon. Can you extract https://github.com/wulkano/kap/pull/750/commits/3b9a5dc5766b7cc272d39d223ec6ca6d83142c9a into a separate PR so we can get that merged?

**Comment by karaggeorge** [comment]
@sindresorhus I implemented part of it already in a different PR. I extracted what I could here: https://github.com/wulkano/kap/pull/775

The rest is dependent on the updated dependencies

**Comment by sindresorhus** [comment]
@karaggeorge I updated to Electron 8 now and built it locally and everything seems to work fine now. Could you test too?

**Comment by karaggeorge** [comment]
After an issue with yarn.lock and fsevents, it now works for me too 👌

**Comment by sindresorhus** [comment]
Woot! At long last.

**Pull request merged**
