### PR TITLE
Remove `cursor:pointer`

### PR DESCRIPTION
**Pull request by sindresorhus**
Native apps do not use the pointer cursor except for links. We should make sure Kap feels as native as possible.

I would also like to remove the grabbing hands from the editor trimmer, but I didn't include that here as I guessed it would be more controversial. Thoughts? Quicktime, for example, does not have a grabbing cursor on the trimming UI.

### CODE REVIEW

**Comment by albinekb** [comment]
I don't agree with this. Why don't native apps use the correct cursor? Personally I don't like to click things that don't have the cursor pointer :'(

**Comment by sallar** [comment]
I agree. cursor doesn't feel "native" on macOS. But that's just my feeling.

**Comment by sindresorhus** [comment]
> Why don't native apps use the correct cursor?

I guess because native generally has consistent and obvious UI, so there's no need, while the web is a mess and there anything could be a button. The pointer was originally meant for links, but at some point, we started using it for everything...

**Comment by timothyis** [comment]
Yeah, I'm not so sure how I feel about this. I think I've gotten used to the fact that kap has `pointer` set for a web like UX but I think removing them wouldn't be an issue and would maybe help with the integration into the desktop environment. 

👍  from me

**Comment by sindresorhus** [comment]
> I would also like to remove the grabbing hands from the editor trimmer, but I didn't include that here as I guessed it would be more controversial. Thoughts?

@timothyis ⬆️

**Comment by timothyis** [comment]
@sindresorhus Sorry, I meant a general thumbs up to this PR and that question. Should have been more specific.

**Comment by timothyis** [comment]
@sindresorhus Just expanding on this:
We have interaction animations that we can do instead of cursors, which isn't necessarily unheard of in native apps.
For example, a button can change colour on hover and you'll know how you should interact with it (let alone the look of it)

**Comment by sindresorhus** [comment]
@timothyis Yup

**Pull request merged**
