### PR TITLE
Allow configure highlight click settings from macOS high sierra

### PR DESCRIPTION
**Pull request by pettomartino**
Addressing Issue https://github.com/wulkano/kap/issues/784

As I mentioned in that issue I've tested this on my machine which runs macOS high sierra

image

Kapture 2020-01-24 at 13 46 37
image
Kapture 2020-01-24 at 13 47 55

### CODE REVIEW

**Comment by karaggeorge** [comment]
@sindresorhus do you remember why we had that check there in the first place? I looked at the commit and it looks like it was part of a bigger PR refactoring the settings, so I don't know what the purpose was exactly. 

From the API page, I don't see any OS version requirements: https://developer.apple.com/documentation/avfoundation/avcapturescreeninput/1385722-capturesmouseclicks

Should we remove that check completely?

**Comment by sindresorhus** [comment]
It was introduced in https://github.com/wulkano/kap/commit/92178c548eaa709bffd0b88e22685b4a80260ad3. See https://github.com/wulkano/kap/issues/477.

// @albinekb

**Comment by albinekb** [comment]
That check was added there because:
>Apple broke the cursor hide/show API in high sierra, so we hide the option there to avoid confusion.

I could not get it to work correctly, I even filed a radar for it see: https://feedbackassistant.apple.com/feedback/5538640

**Comment by karaggeorge** [comment]
@albinekb sounds like there might have been other circumstances that caused it not to work, since @pettomartino  has it working on High Sierra. I think it's okay to remove the check until we encounter the issue again and then we can do some more research then. Thoughts?

**Comment by pettomartino** [comment]
The issue described seem to be related to "show cursor" instead of "highlight click". However, I have tested it as well, and seem to be working too:

image

**Comment by pettomartino** [comment]
Sorry closed by mistake

**Comment by pettomartino** [comment]
I also tested with trackpad and external mouse and both work the same way.
I can't reproduce issues in high sierra.
I got an old MBP 2011 that won't update further than high sierra, so I'm stuck in this version, more people might have same issue, so if you guys are ok with that I think that might be beneficial.

**Pull request merged**
